# Generated by Django 4.1.1 on 2022-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Vaga')),
                ('empregador', models.CharField(max_length=100, verbose_name='Empregador')),
                ('nivel', models.CharField(choices=[('Junior', 'Junior'), ('Pleno', 'Pleno'), ('Sênior', 'Sênior')], max_length=6, verbose_name='Nível da Vaga')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição da vaga')),
                ('tipo_contrato', models.CharField(choices=[('Presencial', 'Presencial'), ('Híbrido', 'Híbrido'), ('Remoto', 'Remoto')], max_length=10, verbose_name='Modalidade da Vaga')),
                ('local', models.CharField(max_length=30, verbose_name='Local da Vaga')),
                ('outras_reg', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Aceita candidatos de outras regiões?')),
                ('requisitos', models.CharField(max_length=50, verbose_name='Requisitos')),
                ('habil_obr', models.CharField(max_length=30, verbose_name='Habilidade')),
                ('salmin', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Mínimo')),
                ('salmax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Máximo')),
                ('beneficios', models.TextField(max_length=100, verbose_name='Benefícios')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
    ]
