# Generated by Django 4.1.1 on 2022-10-14 12:30
from accounts.models import PerfilEmpresas
from django.db import models, migrations
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


def add_grupos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'Candidato'),
        Group(name=u'Empresa')
    ])


def remove_grupos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'Candidato',
            u'Empresa'
        ]
    ).delete()




# def add_grupos2(apps, schema_editor):
#     #apps.get_model('accounts','Empresa').object.filter(user_id = 1).update(user = User.objects.create_user(username='anonymous'))
#     apps.get_model('auth', 'User').objects.filter(user_id=1).update(
#         user=apps.get_model('auth', 'User').objects.create_user(username='anonymous')
#     )

# def criar_empresa(apps, schema_editor):
#     Empresa = apps.get_model('auth', 'User')
# remove_grupos.objects.bulk_create(fantasia = 'Senior',
#      razao_social = 'Senior Sistemas', 
#      cnpj = '80.680.093/0001-81', 
#      ie = '123456789', 
#      endereco = 'Rua da Esperanca', 
#      tamanho = 'pequena', 
#      ramo = 'tecnologia', 
#      cep = '88340-080', 
#      telefone = '(47)3733-2747', 
#      apresentacao = 'ola sou a senior',
#      usuario = User.objects.create(id = 1, password = 'empresa1', is_superuser = False, is_staff = False, username = 'Senior', email = 'contato@seniorsist.com.br' )
#    )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_grupos, remove_grupos )
    ]

remove_grupos