# Generated by Django 4.1.2 on 2022-10-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='beneficios',
            field=models.TextField(help_text='Exemplos: "Vale refeição", "Plano de saúde", etc.', max_length=300, verbose_name='Benefícios'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='requisitos',
            field=models.TextField(help_text='Exemplos: "Formação em nível superior", "Tecnólogo", etc.', max_length=500, verbose_name='Requisitos'),
        ),
    ]
