# Generated by Django 4.1.1 on 2022-11-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_alter_vaga_beneficios_alter_vaga_requisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='outras_reg',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Aceita candidatos de outras regiões?'),
        ),
    ]
