# Generated by Django 4.1.1 on 2022-10-17 17:04

from django.db import migrations
from django.contrib.auth.models import User


def add_users(apps,schema_editor):
    User.objects.create_user('adriano', 'adriano@machado.tec.br','@Karina1977')
    user = User.objects.get(username='adriano')
    user.groups.add('Empresa')
    user.save()



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto')
    ]

    operations = [
        migrations.RunPython(add_users, add_users )
    ]
