# Generated by Django 4.1.1 on 2022-10-17 17:10

from django.db import migrations
from django.contrib.auth.models import User

# DEFAULT_EMPRESAS = (
#     ('Senior','Senior Sistemas','80.680.093/0001-81','1isento','Rua da Esperanca','pequena', 'tecnologia', '88340-080','(47)3733-2747','ola sou a senior','1' )

#     )


# def criar_empresa(apps, schema_editor):
#     Empresa = apps.get_model('accounts', 'PerfilEmpresa')
#     Empresa.objects.bulk_create(
#      fantasia = 'Senior',
#      razao_social = 'Senior Sistemas', 
#      cnpj = '80.680.093/0001-81', 
#      ie = '123456789', 
#      endereco = 'Rua da Esperanca', 
#      tamanho = 'pequena', 
#      ramo = 'tecnologia', 
#      cep = '88340-080', 
#      telefone = '(47)3733-2747', 
#      apresentacao = 'ola sou a senior',
#      usuario = 
#    )

class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_auto_20221017_1404'),
    ]

    operations = [
    ]
