# Generated by Django 4.1.1 on 2022-10-17 17:10

from django.db import migrations


DEFAULT_EMPRESAS = (
    ('Senior','Senior Sistemas','80.680.093/0001-81','1isento','Rua da Esperanca','pequena', 'tecnologia', '88340-080','(47)3733-2747','ola sou a senior','1' )

    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221017_1404'),
    ]

    operations = [
    ]
