# Generated by Django 4.1.1 on 2022-10-17 17:10

from django.db import migrations
from django.contrib.auth.models import User

# DEFAULT_EMPRESAS = (
#     ('Senior','Senior Sistemas','80.680.093/0001-81','1isento','Rua da Esperanca','pequena', 'tecnologia', '88340-080','(47)3733-2747','ola sou a senior','1' )

#     )


def criar_empresa(apps, schema_editor):
    DEFAULT_EMPRESAS = [
        ('AmbevTech', 'AmbevTech LTDA', '81.875.973/0001-76', '', 'RUA THEODORO HOLTRUP, 982 - VILA NOVA','grande', 'tecnologia', '89035-300', '(47)2123-5400', 'Olá, somos a AmbevTech!!',1),
        ('Central Ailos', 'COOPERATIVA CENTRAL DE CREDITO - AILOS', '05.463.212/0001-29', '', 'RUA GENERAL OSORIO, 1180, VELHA','grande', 'financeiro', '89041-002', '(47)3231-4646', 'Olá, somos a Central Ailos',2),
        ('Capgemini', 'CAPGEMINI BRASIL S/A', '65.599.953/0001-63', '', 'ALAMEDA GRAJAU, 60 ANDAR 14SALA1401 - ALPHAVILLE', 'grande', 'tecnologia', '06454-050', '(11) 3908-8180', 'Olá, somos a Capgemini!', 3),
        ('DataInfo', 'DATAINFO SOLUCOES EM TECNOLOGIA DA INFORMACAO LTDA', '05.085.461/0001-28', '', 'AVENIDA PAULISTA, 1636 EDIFPAULISTA CORPORATECONJCOMERCIAL 904 BELA VISTA', 'grande', 'tecnologia', '01310-200', '(11)3287-2301', 'Olá somos a datainfo!',4),
        ('AppFarmacias', 'APP FARMACIA - DESENVOLVIMENTO DE APLICATIVOS LTDA', '27.487.642/0001-13', '', 'Avenida da Universidade, 3089', 'grande', 'tecnologia', '60020-181', '(85)8802-5286', 'Olá somos a farmácias app', 5),
        ('Havan Labs', 'HAVAN S.A', '79.379.491/0016-60', '','Rua 15 de Novembro, 1050 CENTRO', 'grande', 'tecnologia', '88353-100', '(47)3251-5000', 'Se você curte tecnologia, programação e novos desafios o Havan Labs é para você! Somos um time de profissionais voltados para diversas áreas da tecnologia.', 6),
        ('Philips', 'PHILIPS DO BRASIL LTDA', '61.086.336/0001-03', '', 'AVENIDA MARCOS PENTEADO DE ULHOA RODRIGUES, 939 TAMBORE','grande', 'tecnologia', '06460-040', '(11) 2125-0428', 'Olá, somos a philips', 7),
        ('Senior Sistemas', 'SENIOR SISTEMAS S/A', '80.680.093/0008-58', '', 'Rua Marginal Emicol, 21500 Jardim Emicol', 'grande', 'tecnologia', '13312-820', '(47)3221-3300', 'Olá somos a Senior', 8),
        ('T-Systems', 'T-SYSTEMS DO BRASIL LTDA.', '04.426.565/0001-96', '', 'Rua Olimpiadas, 205 3º Andar VILA OLIMPIA', 'grande', 'tecnologia', '04551-000', '(11)2184-2386', 'Olá, somos a tsystems', 9),
        ('Unifique', 'UNIFIQUE TELECOMUNICACOES S/A','02.255.187/0001-08','', 'Rua Duque de Caxias, 831 CENTRO', 'grande', 'tecnologia', '89120-000', '(47)3380-0800', 'Olá, somos a unifique.', 10),
        ('Warren', 'WARREN BRASIL SERVICOS FINANCEIROS LTDA', '26.710.471/0001-87', '', 'Avenida Osvaldo Aranha, 720 Conj 201 BOM FIM', 'grande', 'financeiro', '90035-191', '(51)3237-2273', 'Olá somos a warren', 11)
    ]
    Empresa = apps.get_model('accounts', 'PerfilEmpresas')

    for fantasia, razao_social, cnpj, ie, endereco, tamanho, ramo, cep, telefone, apresentacao, usuario_id in DEFAULT_EMPRESAS:
        Empresa.objects.create(
            fantasia = fantasia,
            razao_social = razao_social, 
            cnpj = cnpj, 
            ie = ie, 
            endereco = endereco, 
            tamanho = tamanho, 
            ramo = ramo, 
            cep = cep, 
            telefone = telefone, 
            apresentacao = apresentacao,
            usuario_id = usuario_id
            )

class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_auto_20221017_1404'),
    ]

    operations = [
        migrations.RunPython(criar_empresa)
    ]
