# Generated by Django 4.1.1 on 2022-10-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_auto_20221017_1410'),
    ]

    operations = [
    ]
