# Generated by Django 4.1.1 on 2022-10-18 02:35

from django.db import migrations
from candidatos.models import Habilidade
#nome, categoria, nivel, descriçao, modalidade, contrato, jornada, local,
# outras_reg, requisitos, salmin, salmax, benefícios, data, pri_habilidade_vaga,
#seg_habilidade_vaga, ter_habilidade_vaga, qua_habilidade_vaga, qui_habilidade_vaga,
#usuario


def criar_vagas(apps,schema_editor):
    DEFAULT_VAGAS = [
        ('Programador back-end', 'Back-end', 'Junior','criação de modelos de dados', 'Presencial', 'CLT', 'Período Integral', 'Blumenau', 'nao', 'Python, Django, SQL, Git/GitHub', 2500.00,3800.00,'Vale transporte, Plano de saúde, Plano odontológico, Vale Refeição.', 208,'','','','',1)
    ]

    vaga = apps.get_model('vagas','Vaga')
    for nome, categoria, nivel, descricao, modalidade, contrato, jornada, local, outras_reg,requisitos,salmin,salmax,beneficios,pri,seg,ter,qua,qui,usuario_id in DEFAULT_VAGAS:
        vaga.objects.create(
            nome = nome,
            categoria = categoria,
            nivel = nivel,
            descricao = descricao,
            modalidede = modalidade,
            contrato = contrato,
            jornada = jornada,
            local = local,
            outras_reg = outras_reg,
            requisitos = requisitos,
            salmin = salmin,
            salmax = salmax,
            beneficios = beneficios,
            pri_habilidade_vaga = pri,
            seg_habilidade_vaga = seg,
            ter_habilidade_vaga = ter,
            qua_habilidade_vaga = qua,
            qui_habilidade_vaga = qui,
            usuario_id = usuario_id
            )

class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_auto_20221017_1737'),
    ]

    operations = [
        migrations.RunPython(criar_vagas)
    ]
