INSERT INTO candidatos_habilidade (habilidade)
	VALUES
    ("ABAP"),
    ("ABNF"),
    ("Administrador de sistema"),
    ("ADVPL"),
    ("Agda"),
    ("AgilePHP"),
    ("Ajax"),
    ("Akelos"),
    ("Android"),
    ("Android Studio"),
    ("Angular"),
    ("Ant Build System"),
    ("Apex"),
    ("API"),
    ("APL"),
    ("Arduino"),
    ("Assembly"),
    ("Atomik"),
    ("AWS RDS (Relational Database Service)"),
    ("Bash"),
    ("Beego"),
    ("Big Data"),
    ("Bootstrap"),
    ("Bottle"),
    ("C"),
    ("C#"),
    ("C++"),
    ("C2hs Haskell"),
    ("CakePHP"),
    ("Catalyst"),
    ("Ceylon"),
    ("Chapel"),
    ("Clean Code"),
    ("Cloud"),
    ("COBOL"),
    ("Cool"),
    ("CSS"),
    ("CSV"),
    ("Data science"),
    ("Delphi"),
    ("Design Pattern"),
    ("DevOps"),
    ("Diff"),
    ("Django"),
    ("Docker"),
    ("echo"),
    ("Entity framework"),
    ("ERP"),
    ("Excel"),
    ("Factor"),
    ("Figma"),
    ("Filtrscript"),
    ("Firebase"),
    ("Firebird"),
    ("Flask"),
    ("Flex"),
    ("Flight"),
    ("Formatted"),
    ("FuelPHP"),
    ("GAP"),
    ("GAS"),
    ("G-code"),
    ("GDB"),
    ("Gin"),
    ("Git"),
    ("Glyph"),
    ("Google Analytics"),
    ("Google Cloud"),
    ("Google Web Toolkit"),
    ("Grammatical Framework"),
    ("Groovy"),
    ("Grok"),
    ("Hack"),
    ("Halcyon"),
    ("Haskell"),
    ("Haxe"),
    ("Heroku"),
    ("Hord"),
    ("HTML"),
    ("HTTP"),
    ("Hy"),
    ("IDL"),
    ("Idris"),
    ("IGOR Pro"),
    ("loke"),
    ("iOS"),
    ("Isabelle ROOT"),
    ("J"),
    ("Jade"),
    ("Jasmin"),
    ("Jasper"),
    ("Java"),
    ("JavaEE"),
    ("JavaScript"),
    ("JavaScriptMVC"),
    ("Java Server Pages"),
    ("Jest"),
    ("Jflex"),
    ("jQuery"),
    ("JSON"),
    ("Julia"),
    ("Jupyter Notebook"),
    ("Kanban"),
    ("KiCard"),
    ("Kit"),
    ("Koa"),
    ("Kohana"),
    ("LabVIEW"),
    ("Lasso"),
    ("Latte"),
    ("Lean"),
    ("Lemmachine"),
    ("Less"),
    ("Lex"),
    ("Limbo"),
    ("Linux"),
    ("Linux Kernel Module"),
    ("Liquid"),
    ("LiveScript"),
    ("LLVM"),
    ("Logos"),
    ("Logtalk"),
    ("Machine learning"),
    ("Mako"),
    ("MariaDB"),
    ("Markdown"),
    ("Martini"),
    ("Mask"),
    ("Mason"),
    ("Mate"),
    ("Mathematica"),
    ("Matlab"),
    ("Max"),
    ("MAXScript"),
    ("Mercury"),
    ("Metal"),
    ("Mflow"),
    ("Monkey"),
    ("Moocode"),
    ("MoonScript"),
    ("MQL4"),
    ("MQL5"),
    ("MTML"),
    ("MUF"),
    ("MVC"),
    ("MySQL"),
    ("Nacy"),
    ("Nerve"),
    ("nesC"),
    (".NET"),
    (".NET Core"),
    ("NetLinx"),
    ("NetLogo"),
    ("Ninja"),
    ("Nit"),
    ("Nitro"),
    ("Node.js"),
    ("Nodemachine"),
    ("Noir"),
    ("NoSQL"),
    ("Nu"),
    ("NumPy"),
    ("ObjDump"),
    ("Objective-C"),
    ("ObjectiveC++"),
    ("Ooc"),
    ("Opa"),
    ("ORACLE"),
    ("Orbit"),
    ("Org"),
    ("Ox"),
    ("Oxygene"),
    ("Oz"),
    ("Pan"),
    ("Pandas"),
    ("Papyrus"),
    ("Parrot"),
    ("Parrot Assembly"),
    ("Pascal"),
    ("PAWN"),
    ("PeopleCode"),
    ("Perfect"),
    ("Perl"),
    ("Perl6"),
    ("Phalcon"),
    ("Phoenix"),
    ("PhoneGap"),
    ("Photoshop"),
    ("PHP "),
    ("PHPUnit"),
    ("Pic"),
    ("Picard"),
    ("Pickle"),
    ("Play"),
    ("PLSQL"),
    ("Pony"),
    ("POO"),
    ("PostgreSQL"),
    ("PostScript"),
    ("PowerShell"),
    ("Prado"),
    ("Processing"),
    ("Pure Data"),
    ("Pure Script"),
    ("PWA"),
    ("Pyramid"),
    ("PyTest"),
    ("Python"),
    ("PyTorch"),
    ("QA - Quality Assurance"),
    ("Qcodo"),
    ("Racket"),
    ("RAML"),
    ("Rascal"),
    ("Ratpack"),
    ("Raw token data"),
    ("Rdoc"),
    ("Red"),
    ("Redcode"),
    ("Redux"),
    ("RenderScript"),
    ("Rmarkdown"),
    ("Roma"),
    ("Rouge"),
    ("Ruby"),
    ("RUNOFF"),
    ("Rust"),
    ("Sage"),
    ("SAP"),
    ("SAS"),
    ("Sass"),
    ("Scala"),
    ("Selenium"),
    ("Self"),
    ("SEO"),
    ("Server"),
    ("Shell"),
    ("Shell Script"),
    ("ShellSession"),
    ("Shen"),
    ("simples"),
    ("Sin"),
    ("Sinatra"),
    ("Slash"),
    ("SQF"),
    ("SQL"),
    ("SQLite"),
    ("SQLPL"),
    ("SQL Server"),
    ("Stylus"),
    ("Testes automatizados"),
    ("Testes de Regressão"),
    ("Testes Funcionais"),
    ("Testes Unitários"),
    ("TeX"),
    ("Text"),
    ("TI Program"),
    ("T-SQL"),
    ("Turbine"),
    ("Visual Basic"),
    ("Volt"),
    ("Vork"),
    ("web2Py"),
    ("Web API"),
    ("WebGUI"),
    ("Web Service"),
    ("WordPress"),
    ("X10"),
    ("xBase"),
    ("XML"),
    ("Xojo"),
    ("Xquery"),
    ("XS"),
    ("Zend"),
    ("Zephir"),
    ("Zope"),
    ("Zotonic");
