# Generated by Django 4.1.1 on 2022-09-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaRamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo', models.CharField(max_length=100, verbose_name='Ramo da empresa')),
            ],
            options={
                'verbose_name': 'Ramo da empresa',
                'verbose_name_plural': 'Ramo das empresas',
            },
        ),
        migrations.CreateModel(
            name='EmpresaTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=100, verbose_name='Tamanho da Empresa')),
            ],
            options={
                'verbose_name': 'Tamanho da empresa',
                'verbose_name_plural': 'Tamanho das empresas',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresaramo', verbose_name='Ramo da empresa')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresatamanho', verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
