# Generated by Django 4.1 on 2022-09-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='EmpresaRamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo', models.CharField(max_length=100, verbose_name='Ramo da empresa')),
            ],
            options={
                'verbose_name': 'Ramo da empresa',
                'verbose_name_plural': 'Ramo das empresas',
            },
        ),
        migrations.CreateModel(
            name='EmpresaTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=100, verbose_name='Tamanho da Empresa')),
            ],
            options={
                'verbose_name': 'Tamanho da empresa',
                'verbose_name_plural': 'Tamanho das empresas',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidades', models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('ts', 'TypeScript'), ('dj', 'Django'), ('php', 'PHP')], max_length=15, verbose_name='Habilidade')),
                ('tempo', models.CharField(choices=[('0-1-anos', '0-1 anos'), ('1-2-anos', '1-2 anos'), ('2-3-anos', '2-3 anos'), ('3-4-anos', '3-4 anos'), ('4-5-anos', '4-5 anos'), ('5+-anos', '5+ anos')], default='Unspecified', max_length=15, verbose_name='Tempo')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['habilidades'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveis',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresaramo', verbose_name='Ramo da empresa')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresatamanho', verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereco')),
                ('data_nasc', models.CharField(max_length=10, verbose_name='Data de Nascimento')),
                ('perfil_linkedin', models.CharField(max_length=100, verbose_name='Linkedin')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area', verbose_name='Area')),
                ('habilidades', models.ManyToManyField(to='app.habilidades')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nivel', verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['area'],
            },
        ),
    ]
