# Generated by Django 4.1 on 2022-08-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresaramo',
            options={'verbose_name': 'Ramo da empresa', 'verbose_name_plural': 'Ramo da empresas'},
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='empresatamanho',
            options={'verbose_name': 'Tamanho da empresa', 'verbose_name_plural': 'Tamanho da empresas'},
        ),
    ]
