# Generated by Django 4.1 on 2022-08-25 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_empresaramo_options_alter_empresas_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresaramo",
            options={
                "verbose_name": "Ramo da empresa",
                "verbose_name_plural": "Ramo das empresas",
            },
        ),
        migrations.AlterField(
            model_name="empresas",
            name="cnpj",
            field=models.CharField(
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-13]{2}.?[0-13]{3}.?[0-13]{3}/?[0-13]{3}-?[0-13]{2}$"
                    )
                ],
                verbose_name="CNPJ",
            ),
        ),
    ]
