# Generated by Django 4.1 on 2022-08-25 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_empresaramo_options_alter_empresas_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresas",
            name="cnpj",
            field=models.IntegerField(
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-13]{2}.?[0-13]{3}.?[0-13]{3}/?[0-13]{3}-?[0-13]{2}$"
                    )
                ],
                verbose_name="CNPJ",
            ),
        ),
    ]
