# Generated by Django 4.1 on 2022-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_empresas_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
    ]
