# Generated by Django 4.1 on 2022-09-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_area_habilidades_nivel_pessoas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='candidato',
            options={'ordering': ['area'], 'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='habilidades',
            options={'ordering': ['nome'], 'verbose_name': 'Habilidade', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveis'},
        ),
        migrations.AlterModelOptions(
            name='pessoas',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='habilidades',
            name='tempo',
            field=models.CharField(choices=[('1', '0-1 anos'), ('2', '1-2 anos'), ('3', '2-3 anos'), ('4', '3-4 anos'), ('5', '4-5 anos'), ('6', '5+ anos')], default='#', max_length=100, verbose_name='Tempo'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='habilidades',
            field=models.ManyToManyField(to='app.habilidades'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.DeleteModel(
            name='HabilidadexCandidatos',
        ),
    ]
