# Generated by Django 4.1.1 on 2022-09-18 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, null=True, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='CPF')),
                ('cep', models.CharField(max_length=9, null=True, verbose_name='CEP')),
                ('data_nasc', models.DateField(max_length=10, null=True, verbose_name='Data de Nascimento')),
                ('github', models.CharField(default='#', max_length=100, verbose_name='GitHub')),
                ('linkedin', models.CharField(default='#', max_length=100, verbose_name='Linkedin')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('descricao', models.TextField(max_length=200, null=True, verbose_name='Descrição')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
