# Generated by Django 4.1.1 on 2022-11-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilCandidatos',
        ),
    ]
