# Generated by Django 4.1.1 on 2022-09-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=50)),
                ('data_nasc', models.CharField(max_length=10, verbose_name='Data de Nascimento')),
                ('github', models.CharField(default='#', max_length=100, verbose_name='GitHub')),
                ('linkedin', models.CharField(default='#', max_length=100, verbose_name='Linkedin')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('ts', 'TypeScript'), ('dj', 'Django'), ('php', 'PHP')], max_length=15, verbose_name='Habilidade')),
                ('experiencia', models.CharField(choices=[('0-1-anos', '0-1 anos'), ('1-2-anos', '1-2 anos'), ('2-3-anos', '2-3 anos'), ('3-4-anos', '3-4 anos'), ('4-5-anos', '4-5 anos'), ('5+-anos', '5+ anos')], default='Unspecified', max_length=15, verbose_name='Tempo de experiência')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('full_stack', 'Full-Stack'), ('fron_end', 'Front-End'), ('back_end', 'Back-End'), ('mobile', 'Mobile')], max_length=10, verbose_name='Área')),
                ('nivel', models.CharField(choices=[('senior', 'Sênior'), ('pleno', 'Pleno'), ('junior', 'Junior')], max_length=6, verbose_name='Nível')),
                ('contrato', models.CharField(choices=[('estagio', 'Estágio'), ('pj', 'PJ'), ('clt', 'CLT')], max_length=7, verbose_name='Contrato')),
                ('local', models.CharField(choices=[('presencial', 'Presencial'), ('hibrido', 'Híbrido'), ('remoto', 'Remoto')], max_length=10, verbose_name='Local')),
                ('salario', models.IntegerField(verbose_name='Salário desejado')),
                ('habilidades', models.ManyToManyField(to='candidatos.habilidades')),
            ],
            options={
                'verbose_name': 'Curriculo',
                'verbose_name_plural': 'Curriculos',
            },
        ),
    ]
