# Generated by Django 4.1.1 on 2022-09-21 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('Django', 'Django'), ('PHP', 'PHP')], max_length=15, null=True, verbose_name='Habilidade')),
                ('experiencia', models.CharField(choices=[('0-1-anos', '0-1 anos'), ('1-2-anos', '1-2 anos'), ('2-3-anos', '2-3 anos'), ('3-4-anos', '3-4 anos'), ('4-5-anos', '4-5 anos'), ('5+-anos', '5+ anos')], default='Unspecified', max_length=15, null=True, verbose_name='Tempo de experiência')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('full_stack', 'Full-Stack'), ('fron_end', 'Front-End'), ('back_end', 'Back-End'), ('mobile', 'Mobile')], max_length=10, null=True, verbose_name='Área')),
                ('nivel', models.CharField(choices=[('senior', 'Sênior'), ('pleno', 'Pleno'), ('junior', 'Junior')], max_length=6, null=True, verbose_name='Nível')),
                ('contrato', models.CharField(choices=[('estagio', 'Estágio'), ('pj', 'PJ'), ('clt', 'CLT')], max_length=7, null=True, verbose_name='Contrato')),
                ('local', models.CharField(choices=[('presencial', 'Presencial'), ('hibrido', 'Híbrido'), ('remoto', 'Remoto')], max_length=10, null=True, verbose_name='Local')),
                ('salario', models.IntegerField(null=True, verbose_name='Salário desejado')),
                ('habilidades', models.ManyToManyField(to='candidatos.habilidades')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curriculo',
                'verbose_name_plural': 'Curriculos',
            },
        ),
    ]
