# Generated by Django 4.1.1 on 2022-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculo',
            old_name='local',
            new_name='modalidade',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='perfil',
        ),
        migrations.AddField(
            model_name='curriculo',
            name='categoria',
            field=models.CharField(choices=[('full_stack', 'Full-Stack'), ('front_end', 'Front-End'), ('back_end', 'Back-End'), ('mobile', 'Mobile')], max_length=10, null=True, verbose_name='Área'),
        ),
    ]
