# Generated by Django 4.1.2 on 2022-10-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidade',
            name='habilidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Habilidade'),
        ),
    ]
