# Generated by Django 4.1.1 on 2022-09-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidades',
            name='habilidade',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('Django', 'Django'), ('PHP', 'PHP')], max_length=15, verbose_name='Habilidade'),
        ),
    ]
