# Generated by Django 4.1.1 on 2022-09-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_alter_candidatos_data_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='data'),
        ),
    ]
