# Generated by Django 4.1.1 on 2022-10-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_alter_habilidade_habilidade'),
    ]

    operations = [
    ]
