# Generated by Django 4.1.1 on 2022-09-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_alter_habilidades_habilidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatos',
            options={},
        ),
    ]
