# Generated by Django 4.1.1 on 2022-10-24 13:57

from unittest.mock import DEFAULT
from django.db import migrations


def criar_curriculo(apps, schema_editor):
    DEFAULT_CURRICULO = [
        ('Front-end', 'Junior', 'CLT', 'Remoto', 3200.00, 208, 44, 79, 65, 103, 15),
        ('Front-end', 'Junior', 'CLT', 'Remoto', 3200.00, 208, 44, 79, 65, 103, 14),
        ('Back-end', 'Junior', 'PJ', 'Remoto', 6000.00, 208, 44, 79, 65, 103, 13),
        ('Back-end', 'Junior', 'CLT', 'Remoto', 3200.00, 208, 44, 79, 65, 103, 18),
        ('Back-end', 'Junior', 'CLT', 'Remoto', 3500.00, 208, 44, 79, 65, 103, 12),
        ('Back-end', 'Junior', 'CLT', 'Hibrido', 3000.00, 208, 44, 79, 65, 103, 19),
        ('Full-stack', 'Junior', 'CLT', 'Remoto', 3200.00, 208, 44, 79, 65, 103, 16),
        ('Back-end', 'Junior', 'CLT', 'Remoto', 3200.00, 208, 44, 79, 65, 103, 17),
        
    ]

    Curriculo = apps.get_model('candidatos','Curriculo')

    for categoria, nivel, contrato, modalidade, salario, pri_habilidade_candidato,seg_habilidade_candidato, ter_habilidade_candidato, qua_habilidade_candidato, qui_habilidade_candidato, usuario in DEFAULT_CURRICULO:
        Curriculo.objects.create(
            categoria = categoria,
            nivel = nivel,
            contrato = contrato,
            modalidade = modalidade,
            salario = salario,
            pri_habilidade_candidato_id = pri_habilidade_candidato,
            seg_habilidade_candidato_id = seg_habilidade_candidato,
            ter_habilidade_candidato_id = ter_habilidade_candidato,
            qua_habilidade_candidato_id = qua_habilidade_candidato,
            qui_habilidade_candidato_id = qui_habilidade_candidato,
            usuario_id = usuario

        )

class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_auto_20221024_0941'),
    ]

    operations = [
        migrations.RunPython(criar_curriculo)
    ]
