# Generated by Django 4.1.1 on 2022-10-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_alter_habilidade_habilidade'),
        ('candidatos', '0005_auto_20221024_1057'),
    ]

    operations = [
    ]
